#python3.11
FROM ubuntu:22.04

#ENV TZ=Asia/Shanghai

RUN sed -i s@/archive.ubuntu.com//@/mirrors.aliyun.com/@g /etc/apt/sources.list \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && apt-get clean

RUN set -eux \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
        python3.11 python3-pip build-essential postgresql-client gcc libpq-dev libxml2-dev libxslt-dev zlib1g-dev libsqlite3-dev python3-dev curl vim

