"""update protal deploy

Revision ID: 332195d7e911
Revises: 95faddc1ecd4
Create Date: 2023-03-01 15:59:43.891407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '332195d7e911'
down_revision = '95faddc1ecd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_portal_deploy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新者'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新日期'),
    sa.Column('title', sa.String(length=20), nullable=False, comment='主标题'),
    sa.Column('sub_title', sa.String(length=80), nullable=False, comment='副标题'),
    sa.Column('img', sa.String(length=280), nullable=False, comment='图片链接/地址'),
    sa.Column('link', sa.String(length=300), nullable=True, comment='链接'),
    sa.Column('color', sa.String(length=30), nullable=True, comment='背景颜色'),
    sa.Column('category', sa.String(length=15), nullable=False, comment='banner/平台特点/亮点说明'),
    sa.Column('state', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_portal_deploy')
    # ### end Alembic commands ###
