"""update user_pms

Revision ID: 652714304116
Revises: 866122db98c2
Create Date: 2023-02-13 14:57:28.715575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652714304116'
down_revision = '866122db98c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['bam_role.id'], name='fk_users_roles_bam_role_role_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['bam_user.id'], name='fk_users_roles_bam_user_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bam_permissions', 'name',
               existing_type=sa.VARCHAR(length=30),
               comment='模块/菜单/操作标题(英文)',
               existing_comment='模块/菜单/操作标题',
               existing_nullable=False)
    op.alter_column('bam_permissions', 'category',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.create_unique_constraint(None, 'bam_permissions', ['name'])
    op.drop_constraint('fk_bam_user_bam_role_id_role', 'bam_user', type_='foreignkey')
    op.drop_column('bam_user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bam_user', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_bam_user_bam_role_id_role', 'bam_user', 'bam_role', ['role'], ['id'])
    op.drop_constraint(None, 'bam_permissions', type_='unique')
    op.alter_column('bam_permissions', 'category',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('bam_permissions', 'name',
               existing_type=sa.VARCHAR(length=30),
               comment='模块/菜单/操作标题',
               existing_comment='模块/菜单/操作标题(英文)',
               existing_nullable=False)
    op.drop_table('users_roles')
    # ### end Alembic commands ###
