"""init user pms

Revision ID: 866122db98c2
Revises: 
Create Date: 2023-02-08 16:33:20.358069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866122db98c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bam_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新者'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新日期'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级ID'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='模块/菜单/操作标题'),
    sa.Column('value', sa.String(length=50), nullable=True, comment='描述'),
    sa.Column('uri', sa.String(length=200), nullable=True, comment='权限识别标记1'),
    sa.Column('tag', sa.String(length=200), nullable=True, comment='权限识别标记2'),
    sa.Column('category', sa.String(length=15), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True, comment='是否启用，默认True（启用）'),
    sa.Column('order', sa.Integer(), nullable=True, comment='功能菜单排序'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bam_role',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=30), nullable=True, comment='说明'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bam_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新者'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新日期'),
    sa.Column('category', sa.String(length=15), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False, comment='用户名'),
    sa.Column('en_name', sa.String(length=20), nullable=False, comment='英文用户名'),
    sa.Column('email', sa.String(length=80), nullable=False, comment='邮箱'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['bam_role.id'], name='fk_bam_user_bam_role_id_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('en_name')
    )
    op.create_table('permissionss_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permissions'], ['bam_permissions.id'], name='fk_permissionss_roles_bam_permissions_permissions_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role'], ['bam_role.id'], name='fk_permissionss_roles_bam_role_role_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissionss_roles')
    op.drop_table('bam_user')
    op.drop_table('bam_role')
    op.drop_table('bam_permissions')
    # ### end Alembic commands ###
