"""update protal

Revision ID: 95faddc1ecd4
Revises: 9d476caebad9
Create Date: 2023-02-28 18:04:45.979207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95faddc1ecd4'
down_revision = '9d476caebad9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_portal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新者'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建日期'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新日期'),
    sa.Column('title', sa.String(length=20), nullable=False, comment='主标题'),
    sa.Column('sub_title', sa.String(length=80), nullable=False, comment='副标题'),
    sa.Column('img', sa.String(length=280), nullable=False, comment='图片链接/地址'),
    sa.Column('link', sa.String(length=300), nullable=False, comment='链接'),
    sa.Column('color', sa.String(length=30), nullable=False, comment='背景颜色'),
    sa.Column('category', sa.Integer(), nullable=False, comment='banner/平台特点/亮点说明'),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_portal')
    # ### end Alembic commands ###
