"""update state

Revision ID: 9d476caebad9
Revises: fed04117f8a4
Create Date: 2023-02-28 16:39:45.021246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d476caebad9'
down_revision = 'fed04117f8a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_portal', 'state',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('content_model', sa.Column('state', sa.Integer(), nullable=True))
    op.alter_column('content_model', 'img',
               existing_type=sa.VARCHAR(length=200),
               comment='图片地址',
               existing_comment='模型名称',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_model', 'img',
               existing_type=sa.VARCHAR(length=200),
               comment='模型名称',
               existing_comment='图片地址',
               existing_nullable=False)
    op.drop_column('content_model', 'state')
    op.alter_column('content_portal', 'state',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
