"""update content

Revision ID: fed04117f8a4
Revises: 92d0481d90e3
Create Date: 2023-02-24 17:40:45.091828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fed04117f8a4'
down_revision = '92d0481d90e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_model', sa.Column('index', sa.Integer(), nullable=False, comment='排序'))
    op.add_column('content_model', sa.Column('title', sa.String(length=200), nullable=False, comment='模型名称'))
    op.add_column('content_model', sa.Column('sub_title', sa.String(length=200), nullable=False, comment='副标题'))
    op.add_column('content_model', sa.Column('img', sa.String(length=200), nullable=False, comment='模型名称'))
    op.add_column('content_model', sa.Column('description', sa.Text(), nullable=False, comment='描述(整个大文本)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_model', 'description')
    op.drop_column('content_model', 'img')
    op.drop_column('content_model', 'sub_title')
    op.drop_column('content_model', 'title')
    op.drop_column('content_model', 'index')
    # ### end Alembic commands ###
