---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: changjiang
  labels:
    app: user
    service: user
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: user
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: changjiang-user
  labels:
    account: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-v1
  namespace: changjiang
  labels:
    app: user
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      version: v1
  template:
    metadata:
      labels:
        app: user
        version: v1
    spec:
      serviceAccountName: changjiang-user
      containers:
      - name: user
        image: containers.git.digitalbrain.cn/engineering-group/changjiang.user:2023-02-15.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cj-service-config
          mountPath: /etc/changjiang/config.yaml
          subPath: user
      volumes:
      - name: cj-service-config
        configMap:
          name: cj-service-config
          items:
          - key: user
            path: user
      imagePullSecrets:
      - name: db-container
---