---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: changjiang
  labels:
    app: frontend
    service: frontend
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: changjiang-frontend
  labels:
    account: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
  namespace: changjiang
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      serviceAccountName: changjiang-frontend
      containers:
      - name: frontend
        image: containers.git.digitalbrain.cn/engineering-group/changjiang.frontend:2023-02-20.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cj-service-config
          mountPath: /etc/changjiang/config.yaml
          subPath: frontend
      volumes:
      - name: cj-service-config
        configMap:
          name: cj-service-config
          items:
          - key: frontend
            path: frontend
      imagePullSecrets:
      - name: db-container
---
