---
apiVersion: v1
kind: Service
metadata:
  name: content
  namespace: changjiang
  labels:
    app: content
    service: content
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: content
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: changjiang-content
  labels:
    account: content
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-v1
  namespace: changjiang
  labels:
    app: content
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content
      version: v1
  template:
    metadata:
      labels:
        app: content
        version: v1
    spec:
      serviceAccountName: changjiang-content
      containers:
      - name: content
        image: containers.git.digitalbrain.cn/engineering-group/changjiang.content:2023-02-24.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cj-service-config
          mountPath: /etc/changjiang/config.yaml
          subPath: content
      volumes:
      - name: cj-service-config
        configMap:
          name: cj-service-config
          items:
          - key: content
            path: content
      imagePullSecrets:
      - name: db-container
---