# syntax=docker/dockerfile:1.4
ARG BASE_IMG=containers.git.digitalbrain.cn/engineering-group/changjiang.backend-base:2023-03-10.4
FROM $BASE_IMG
WORKDIR /source/services/user_pms


# python dependence
COPY ./user_pms/requirements.txt .
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
